# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'fitness-app-ios' do
  # Pods for fitness-app-ios
  pod 'SwiftKeychainWrapper', '~> 3.4'

  target 'fitness-app-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fitness-app-iosUITests' do
    # Pods for testing
  end

end
